apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.1.0
    init: confluentinc/confluent-init-container:2.3.1
  dataVolumeCapacity: 10Gi
  metricReporter:
    enabled: false
  configOverrides:
    server:
      - offsets.topic.replication.factor=1
      - confluent.tier.metadata.replication.factor=1
      - transaction.state.log.replication.factor=1
      - confluent.cluster.link.metadata.topic.replication.factor=1
      - default.replication.factor=1
      - confluent.metrics.reporter.topic.replicas=1
      - auto.create.topics.enable=true
