apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: centos
  name: centos
  namespace: confluent
spec:
  containers:
  - image: centos:8
    name: centos
    command: ["/bin/sleep", "3650d"]
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
