apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos8-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos8-app
  template:
    metadata:
      labels:
        app: centos8-app
    spec:
      containers:
        - name: centos8-container
          image: centos:8
          command: ["sleep", "3600"]
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: java-volume
              mountPath: /usr/lib/jvm/java-11-openjdk
      volumes:
        - name: java-volume
          emptyDir: {}
      initContainers:
        - name: install-java
          image: centos:8
          command: ["/bin/sh", "-c"]
          args: ["while ! dnf install -y java-11-openjdk; do sleep 1; done"]
          volumeMounts:
            - name: java-volume
              mountPath: /usr/lib/jvm/java-11-openjdk
