apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: ab-example-topic
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 3
  kafkaClusterRef:
    name: kafka
  configs:
    min.insync.replicas: "1"
    retention.ms: "86400000"